[connections.snowflake]
account = "NONGWKL-MOB76819"
user = "SupriyaK"
password = "L3arnSFlake"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
